swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully  # Correction du message de description
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:  # Nouvel endpoint pour la gestion des transactions
    get:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - Transactions
      summary: Get all transactions for the current month, grouped by account
      description: API to retrieve all transactions for the current month, grouped by account
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - Transactions
      summary: Add a new transaction
      description: API to add a new transaction (modifies existing transaction information)
      parameters:
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction added successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:  # Endpoint pour une transaction spécifique
    get:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - Transactions
      summary: Get details of a specific transaction
      description: API to retrieve details of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - Transactions
      summary: Update transaction information
      description: API to update information of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to update
        - in: body
          name: body
          description: Updated transaction information
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []  # Utilise l'authentification Bearer pour sécuriser l'endpoint
      tags:
        - Transactions
      summary: Delete transaction information
      description: API to delete information of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to delete
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string  # Correction du type à string
        description: user username
  UserProfile:
    properties:
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user username
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  LoginResponse:
    properties:
      token:
        type: string
        description: authentication token
      user:
        $ref: '#/definitions/UserProfile'  # Ajout de la référence au profil utilisateur dans la réponse de login
  ApiResponse:
    properties:
      message:
        type: string
        description: response message
      data:
        type: object
        description: additional data
  Transaction:
    properties:
      id:
        type: string
        description: transaction ID
      amount:
        type: number
        description: transaction amount
      date:
        type: string
        format: date-time
        description: transaction date
      description:
        type: string
        description: transaction description
      accountId:
        type: string
        description: account ID related to the transaction
